In [107]:
import numpy as np

In [108]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

print(np_array[1].astype(float)*2)


3.0


In [109]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
print(float(np_array[1])*2)

3.0


In [110]:
str(np_array[1])

'1.5'

In [111]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
sum(np_array[my_mask])

np.int64(49)

In [112]:
x=[1, 2, 3]
x.append([4, 5, 6])
x[3]

[4, 5, 6]

In [113]:
import math
x, y = 3, 4
z = math.sqrt(x**2 + y**2)
print(x, y, z)

3 4 5.0


In [114]:
list = [['Apple', 0.99],['Banana', 0.59], ['Orange', 1.29]]

for i in range(len(list)):
    print(f'{list[i][0]:10} ${list[i][1]:>5}')

Apple      $ 0.99
Banana     $ 0.59
Orange     $ 1.29


In [115]:
try:
    user_input = float(input('Enter the student\'s score:'))
    if 70 <= user_input <= 100:
        print("The student\'s letter grade is: A")
    elif 50 <= user_input <= 69:
        print("The student\'s letter grade is: B")
    elif 35 <= user_input <= 49:
        print("The student\'s letter grade is: C")
    elif 0 <= user_input <= 34:
        print("The student\'s letter grade is: Fail")
    else:
        print("Error: Please input the student\'s score again.")

except:
    print("not a number")


not a number


In [131]:
def factorial(n):
    try:
        int(n)
        if n==0:
            return 1
        elif n<0:
            return "neg number"
        else:
            x = n
            for i in range(1,n):
                x *= i
            return x
    except:
        print("not an integer")

factorial(1.4)


not an integer


In [134]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0::2])

['a1', 'c3', 'e5', 'g7', 'i9']


In [135]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

for i in range(len(py_list)):
    if i%2==0:
        print(py_list[i])
    else:
        continue

a1
c3
e5
g7
i9


In [136]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
nparray=np.array(numbers)
sum(nparray==1)

np.int64(9)

In [156]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
x1 = np.array(x_1)
x2 = np.array(x_2)

In [159]:
x1x2 = x1 * x2
x1squared = x1 ** 2
x2squared = x2 ** 2

r = (10*x1x2.sum() 
     - x1.sum() * x2.sum())/np.sqrt((10*x1squared.sum() - 
    (x1.sum()) ** 2) * (10*x2squared.sum() - (x2.sum()) ** 2))
print ('r =', r)

r = 0.9871796626270701


In [172]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


np_array_2d[(np_array_2d[:,0]).astype(int)%2==1,1]
# woww this one kinda tricky


array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [171]:
np_array_2d = np.array([[66, 50, 57, -1, -1],
                        [92, -1, 88, -1, -1],
                        [75, -1, -1, 76, -1],
                        [-1, 51, 87, -1, -1],
                        [71, -1, 67, -1, 69]])
np_array_2d[np_array_2d<50] = -1
np_array_2d[np_array_2d>50] = 1
np_array_2d[np_array_2d==50] = 0

# I CAN JUST SET STUFF

print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [ ]:
for power in range(5):
    number = 10**power
    if number > 5000:
        break
    print(power, number)

In [ ]:
power = 0
while power < 5:
    number = 10**power
    if number >5000:
        break
    print (power, number)
    power +=1
    

0 1
1 10
2 100
3 1000


In [6]:
for power in range(5):
    if power == 3:
        continue        # Don't proceed further
                        # IN THE CURRENT LOOP
                        # if i == 3
    number = 10**power
    print(power, number)

0 1
1 10
2 100
4 10000


In [22]:
power = 0
while power < 5:
    number = 10**power
    power += 1
    if power == 3:
        continue     # ok one fun thing i realised is that the power +=1
                     #must be before the if power == 3 because if not it just keeps 
                     # checking that the power == 3
    print(power-1, number)

0 1
1 10
3 1000
4 10000


In [23]:
superhero_info={"Natasha Romanoff": "Black Widow",
                "Tony Stark": "Iron Man",
                "Stephen Strange": "Doctor Strange"}

for key, value in superhero_info.items():
    print(f"{key} is Marvel's {value}!")

Natasha Romanoff is Marvel's Black Widow!
Tony Stark is Marvel's Iron Man!
Stephen Strange is Marvel's Doctor Strange!


In [24]:
for key in superhero_info.keys():
    value=superhero_info[key]
    print(f"{key} is Marvel's {value}!")

Natasha Romanoff is Marvel's Black Widow!
Tony Stark is Marvel's Iron Man!
Stephen Strange is Marvel's Doctor Strange!


In [25]:
for value in superhero_info.values():
    print(value)

Black Widow
Iron Man
Doctor Strange


In [26]:
my_short_function = lambda name: f"Hello {name}!"

In [27]:
my_short_function("Super Man")

'Hello Super Man!'

In [28]:
numbers=[[9, 0, -10],
         [8, 1, -11],
         [7, 2, -12],
         [6, 3, -13],
         [5, 4, -14],
         [4, 5, -15],
         [3, 6, -16],
         [2, 7, -17],
         [1, 8, -18],
         [0, 9, -19]]

In [29]:
# Sort by comparing the default key
# (i.e., the 1st element)
sorted(numbers)

[[0, 9, -19],
 [1, 8, -18],
 [2, 7, -17],
 [3, 6, -16],
 [4, 5, -15],
 [5, 4, -14],
 [6, 3, -13],
 [7, 2, -12],
 [8, 1, -11],
 [9, 0, -10]]

In [32]:
# Sort by comparing a custom key
# that uses the 2nd element (index=1)
sorted(numbers, key=lambda x: x[1])

[[9, 0, -10],
 [8, 1, -11],
 [7, 2, -12],
 [6, 3, -13],
 [5, 4, -14],
 [4, 5, -15],
 [3, 6, -16],
 [2, 7, -17],
 [1, 8, -18],
 [0, 9, -19]]

In [33]:
# Using default values
print('I', 'am', 'Batman!')
# Specifying an optional argument
print('I', 'am', 'Batman!', sep='')  

I am Batman!
IamBatman!


In [ ]:
for i in range(5):
    i += 10
    assert i <5, "HELP"
    print(i)

10
11
12
13
14


In [36]:
i = 5
for x in range(10):
    i +=10
    assert i <50, "HELP"
    print(i)

15
25
35
45


AssertionError: HELP